CREATE DATABASE `FightingRooster` DEFAULT CHARACTER SET UTF8MB4;

USE `FightingRooster`;

DROP TABLE IF EXISTS `fighter`;
CREATE TABLE `fighter` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `Name` CHAR(50) NOT NULL DEFAULT '',
  `Title` CHAR(50) NOT NULL DEFAULT '',
  `PowerUds` int NOT NULL DEFAULT '0',
  `Element` CHAR(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

